### ISSUE TITLE
Fix the alignment of results on search

### ISSUE THREAD

**Issue by divyashk** [divyashk/BeatIT-music-downloader#1]
### When the search output is just one video the output is not aligned the right way.  Needs to be aligned in the centre.
Please show the changes with preview before creating a PR.

![Screenshot from 2020-10-19 18-03-17](https://user-images.githubusercontent.com/53950730/96451894-df120980-1235-11eb-8935-e676b6caf714.png)

**Comment by peppeocchi** [comment]
@divyashk please see screenshots below, I did 2 screenshots so you can see how it looks where there are 2 or 1 result

If you're happy with the result I can send the PR

<img width="1522" alt="Screenshot 2020-10-19 at 15 46 20" src="https://user-images.githubusercontent.com/4161743/96459379-5a69c000-1222-11eb-9b99-de59140869e7.png">
<img width="1374" alt="Screenshot 2020-10-19 at 15 46 33" src="https://user-images.githubusercontent.com/4161743/96459396-5dfd4700-1222-11eb-9024-818f7b0519bf.png">

**Comment by Paras-code-007** [comment]
can i work on this issue?

**Comment by divyashk** [comment]
> @divyashk please see screenshots below, I did 2 screenshots so you can see how it looks where there are 2 or 1 result
> 
> If you're happy with the result I can send the PR
> 
> <img alt="Screenshot 2020-10-19 at 15 46 20" width="1522" src="https://user-images.githubusercontent.com/4161743/96459379-5a69c000-1222-11eb-9b99-de59140869e7.png">
> 
> <img alt="Screenshot 2020-10-19 at 15 46 33" width="1374" src="https://user-images.githubusercontent.com/4161743/96459396-5dfd4700-1222-11eb-9024-818f7b0519bf.png">

@peppeocchi  Sure, looks good, create the PR.
